<?php

namespace AppBundle\Repository;

/**
 * TwitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TwitRepository extends \Doctrine\ORM\EntityRepository
{
}
