<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Twit;
use AppBundle\Entity\User;

/**
 * TwitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TwitRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @var User $user
     * @return Twit[]
     */
    public function findAllMyTwits(User $user)
    {
        return $this->createQueryBuilder('twit')
            ->andWhere('twit.user = :user')
            ->setParameter('user', $user)
            ->orderBy('twit.createdAt', 'DESC')
            ->getQuery()
            ->execute();
    }
}
